#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Ember — local dev setup
#
#   ./scripts/setup.sh           First-time setup (or refresh Supabase keys)
#   ./scripts/setup.sh --reset   Same, plus wipe + re-seed the database
#   ./scripts/setup.sh --help    Show this message
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

# ── flags ─────────────────────────────────────────────────────────────────────
DO_RESET=false
for arg in "$@"; do
  case $arg in
    --reset) DO_RESET=true ;;
    --help|-h)
      grep '^#' "$0" | grep -v '#!/' | sed 's/^# \{0,1\}//'
      exit 0 ;;
  esac
done

# ── colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

log()    { echo -e "${BLUE}▶${NC} $*"; }
ok()     { echo -e "${GREEN}✓${NC} $*"; }
warn()   { echo -e "${YELLOW}⚠${NC}  $*"; }
die()    { echo -e "${RED}✗  $*${NC}" >&2; exit 1; }
header() { echo -e "\n${BOLD}── $* ──${NC}"; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ── 1. Prerequisites ──────────────────────────────────────────────────────────
header "1 / 6  Prerequisites"

require() {
  local cmd="$1" install_hint="$2"
  if ! command -v "$cmd" &>/dev/null; then
    die "$cmd not found.  $install_hint"
  fi
  ok "$cmd  $(${cmd} --version 2>&1 | head -1)"
}

require node     "Install Node.js 20+ → https://nodejs.org"
require pnpm     "Run: npm install -g pnpm@9"
require supabase "Run: npm install -g supabase  (or: brew install supabase/tap/supabase)"
require docker   "Install Docker Desktop → https://www.docker.com/products/docker-desktop/"

node_major=$(node -e "process.stdout.write(process.versions.node.split('.')[0])")
[ "$node_major" -ge 20 ] || die "Node.js 20+ required, found $(node --version)"

if ! docker info &>/dev/null; then
  die "Docker is not running.  Start Docker Desktop and try again."
fi
ok "Docker daemon is up"

# ── 2. Install dependencies ───────────────────────────────────────────────────
header "2 / 6  Installing dependencies"
pnpm install --frozen-lockfile
ok "pnpm install complete"

# ── 3. Start Supabase ─────────────────────────────────────────────────────────
header "3 / 6  Supabase"

if supabase status &>/dev/null 2>&1; then
  ok "Supabase already running — skipping start"
else
  log "Starting Supabase (first run pulls Docker images; this takes a minute)..."
  supabase start
fi

# Parse credentials out of supabase status
SUPA_STATUS=$(supabase status 2>&1)

extract() {
  # Try two common label formats across CLI versions
  local val
  val=$(echo "$SUPA_STATUS" | grep -i "$1" | head -1 | sed 's/.*:[[:space:]]*//' | tr -d '[:space:]')
  echo "$val"
}

SUPA_URL=$(extract "API URL")
SUPA_ANON=$(extract "anon key")
SUPA_SERVICE=$(extract "service_role key")

[ -n "$SUPA_URL" ]     || die "Could not parse API URL from 'supabase status'.\nRun 'supabase status' manually and check the output."
[ -n "$SUPA_ANON" ]    || die "Could not parse anon key from 'supabase status'."
[ -n "$SUPA_SERVICE" ] || die "Could not parse service_role key from 'supabase status'."

ok "API URL: $SUPA_URL"

# ── 4. Write .env.local files ─────────────────────────────────────────────────
header "4 / 6  Environment files"

# Update (or create) a single KEY=VALUE line in a file
set_env_var() {
  local file="$1" key="$2" val="$3"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${val}|" "$file"
  else
    echo "${key}=${val}" >> "$file"
  fi
}

write_env() {
  local dest="$1" app_url="${2:-http://localhost:3000}"

  if [ -f "$dest" ]; then
    log "Refreshing Supabase keys in $dest"
    set_env_var "$dest" "NEXT_PUBLIC_SUPABASE_URL"    "$SUPA_URL"
    set_env_var "$dest" "NEXT_PUBLIC_SUPABASE_ANON_KEY" "$SUPA_ANON"
    set_env_var "$dest" "SUPABASE_SERVICE_ROLE_KEY"   "$SUPA_SERVICE"
    set_env_var "$dest" "EXPO_PUBLIC_SUPABASE_URL"    "$SUPA_URL"
    set_env_var "$dest" "EXPO_PUBLIC_SUPABASE_ANON_KEY" "$SUPA_ANON"
  else
    log "Creating $dest"
    cat > "$dest" <<ENVFILE
# Generated by scripts/setup.sh — re-run the script to refresh Supabase keys.
# Everything below OPTIONAL can be left blank; those features just won't work.

# ── Supabase (auto-filled) ────────────────────────────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=${SUPA_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPA_ANON}
SUPABASE_SERVICE_ROLE_KEY=${SUPA_SERVICE}

# Used by mobile / edge functions
EXPO_PUBLIC_SUPABASE_URL=${SUPA_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPA_ANON}

# ── App URL ───────────────────────────────────────────────────────────────────
NEXT_PUBLIC_APP_URL=${app_url}
EXPO_PUBLIC_APP_URL=${app_url}

# ── OPTIONAL: Stripe (payments) ───────────────────────────────────────────────
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=

# ── OPTIONAL: other services ──────────────────────────────────────────────────
ANTHROPIC_API_KEY=       # AI prompt personalisation  → console.anthropic.com
POSTHOG_KEY=             # Analytics                  → posthog.com
SENTRY_DSN=              # Error tracking             → sentry.io
RESEND_API_KEY=          # Transactional email        → resend.com
REVENUECAT_SECRET=       # Mobile subscriptions       → revenuecat.com
REVENUECAT_WEBHOOK_AUTH= # RevenueCat webhook secret
EXPO_ACCESS_TOKEN=       # EAS builds                 → expo.dev
ENVFILE
  fi

  ok "$dest"
}

write_env "apps/web/.env.local"
write_env "apps/admin/.env.local"

# Mobile gets a leaner file (no server-side keys)
if [ -f "apps/mobile/.env.local" ]; then
  log "Refreshing Supabase keys in apps/mobile/.env.local"
  set_env_var "apps/mobile/.env.local" "EXPO_PUBLIC_SUPABASE_URL"     "$SUPA_URL"
  set_env_var "apps/mobile/.env.local" "EXPO_PUBLIC_SUPABASE_ANON_KEY" "$SUPA_ANON"
else
  log "Creating apps/mobile/.env.local"
  cat > "apps/mobile/.env.local" <<ENVFILE
EXPO_PUBLIC_SUPABASE_URL=${SUPA_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${SUPA_ANON}
EXPO_PUBLIC_APP_URL=http://localhost:3000
ENVFILE
fi
ok "apps/mobile/.env.local"

# ── 5. Database ───────────────────────────────────────────────────────────────
header "5 / 6  Database"

if $DO_RESET; then
  log "Resetting database (--reset) — all local data will be wiped..."
  supabase db reset
  ok "Database wiped, migrations applied, seed loaded"
else
  log "Applying pending migrations (skipping seed)..."
  # migration up applies only unapplied migrations; falls back to db reset on
  # fresh containers where the migration history table doesn't exist yet.
  if ! supabase migration up 2>/dev/null; then
    warn "migration up failed (likely a fresh DB) — running db reset instead"
    supabase db reset
  fi
  ok "Database migrations up to date"
  echo ""
  warn "Your existing data was preserved."
  warn "Run  ./scripts/setup.sh --reset  to wipe and re-seed."
fi

# ── 6. Summary ────────────────────────────────────────────────────────────────
header "6 / 6  Ready"

cat <<SUMMARY

  ${GREEN}${BOLD}Ember is ready.${NC}

  ${BOLD}Start everything:${NC}
    pnpm dev

  ${BOLD}URLs:${NC}
    Web app         →  http://localhost:3000
    Admin panel     →  http://localhost:3001
    Supabase Studio →  http://localhost:54323   (DB browser)
    Inbucket        →  http://localhost:54324   (catch-all email)

  ${BOLD}Useful commands:${NC}
    pnpm test                        run unit tests
    pnpm lint                        type-check all packages
    supabase studio                  open DB browser in browser
    supabase logs                    tail all Supabase service logs
    ./scripts/setup.sh --reset       wipe + re-seed the database

  ${YELLOW}Optional:${NC} add STRIPE_SECRET_KEY, ANTHROPIC_API_KEY, etc.
  ${YELLOW}         ${NC} to apps/web/.env.local to enable those features.

SUMMARY
